#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="resources/dotbot"

DOTBOT_BIN="bin/dotbot"
if [ -z "$DOTFILES" ]; then
    BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
    BASEDIR="$DOTFILES"
fi

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${BASEDIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
