# K9s Solarized Skin Contributed by [@graelo](graelo@grael.cc)
# Modified by jdloft for Solarized mode3
#
# The table below is extracted from <https://github.com/gdamore/tcell/blob/bd74010edcb3e8e36c090323c2b1d4a6b182d487/color.go#L846-L861>
# and joined with both the ascii standard names from <https://en.wikipedia.org/wiki/ANSI_escape_code#Colors>
# and the solarized color names from <https://ethanschoonover.com/solarized/>
#
#       "black":                ColorBlack,        black            base02
#       "maroon":               ColorMaroon,       red              red
#       "green":                ColorGreen,        green            green
#       "olive":                ColorOlive,        yellow           yellow
#       "navy":                 ColorNavy,         blue             blue
#       "purple":               ColorPurple,       magenta          magenta
#       "teal":                 ColorTeal,         cyan             cyan
#       "silver":               ColorSilver,       white            base2
#       "gray":                 ColorGray,         brightblack      base03
#       "red":                  ColorRed,          brightred        orange
#       "lime":                 ColorLime,         brightgreen      base01
#       "yellow":               ColorYellow,       brightyellow     base00
#       "blue":                 ColorBlue,         brightblue       base0
#       "fuchsia":              ColorFuchsia,      brightmagenta    violet
#       "aqua":                 ColorAqua,         brightcyan       base1
#       "white":                ColorWhite,        brightwhite      base3
#
# Mode 3 differences:
# color16 base01
# color17 base00
# color18 base0
# color19 violet
# color20 base1
# color21 base03

base03:       &base03   bisque        # base03    color21
base02:       &base02   black         # base02    color00 Black
base01:       &base01   lime          # base01    color16
base00:       &base00   antiquewhite  # base00    color17
base0:        &base0    aquamarine    # base0     color18
base1:        &base1    beige         # base1     color20
base2:        &base2    silver        # base2     color07 White
base3:        &base3    white         # base3     color15 Bright_White
yellow:       &yellow   yellow        # accent    color03 Yellow
orange:       &orange   orange        # accent    color09 Bright_Red
red:          &red      maroon        # accent    color01 Red
magenta:      &magenta  purple        # accent    color05 Magenta
violet:       &violet   azure         # accent    color19
blue:         &blue     navy          # accent    color04 Blue
cyan:         &cyan     teal          # accent    color06 Cyan
green:        &green    green         # accent    color10 Green

background:   &background   default       # transparent
foreground:   &foreground   antiquewhite  # base00
current_line: &current_line silver        # base2
selection:    &selection    silver        # base2
comment:      &comment      beige         # base1

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *magenta
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *blue
    sectionColor: *foreground
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: *base2
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *foreground
    menu:
      fgColor: *foreground
      keyColor: *blue
      numKeyColor: *green
    crumbs:
      fgColor: *base2
      bgColor: *base0
      activeColor: *blue
    status:
      newColor: *base00
      modifyColor: *blue
      addColor: *yellow
      errorColor: *red
      highlightColor: *orange
      killColor: *violet
      completedColor: *green
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *blue
      counterColor: *magenta
      filterColor: *magenta
  views:
    charts:
      bgColor: default
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *base2
      cursorBgColor: *background
      markColor: *magenta
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *magenta
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *green
      colonColor: *base02
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *selection
